# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.sales_order_management_v1_api import SalesOrderManagementV1Api


class TestSalesOrderManagementV1Api(unittest.TestCase):
    """ SalesOrderManagementV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.sales_order_management_v1_api.SalesOrderManagementV1Api()

    def tearDown(self):
        pass

    def test_sales_order_management_v1_add_comment_post(self):
        """
        Test case for sales_order_management_v1_add_comment_post

        
        """
        pass

    def test_sales_order_management_v1_cancel_post(self):
        """
        Test case for sales_order_management_v1_cancel_post

        
        """
        pass

    def test_sales_order_management_v1_get_comments_list_get(self):
        """
        Test case for sales_order_management_v1_get_comments_list_get

        
        """
        pass

    def test_sales_order_management_v1_get_status_get(self):
        """
        Test case for sales_order_management_v1_get_status_get

        
        """
        pass

    def test_sales_order_management_v1_hold_post(self):
        """
        Test case for sales_order_management_v1_hold_post

        
        """
        pass

    def test_sales_order_management_v1_notify_post(self):
        """
        Test case for sales_order_management_v1_notify_post

        
        """
        pass

    def test_sales_order_management_v1_un_hold_post(self):
        """
        Test case for sales_order_management_v1_un_hold_post

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
