# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.body_128 import Body128


class TestBody128(unittest.TestCase):
    """ Body128 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody128(self):
        """
        Test Body128
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.body_128.Body128()
        pass


if __name__ == '__main__':
    unittest.main()
