# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.catalog_data_product_option_extension_interface import CatalogDataProductOptionExtensionInterface


class TestCatalogDataProductOptionExtensionInterface(unittest.TestCase):
    """ CatalogDataProductOptionExtensionInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCatalogDataProductOptionExtensionInterface(self):
        """
        Test CatalogDataProductOptionExtensionInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.catalog_data_product_option_extension_interface.CatalogDataProductOptionExtensionInterface()
        pass


if __name__ == '__main__':
    unittest.main()
