# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.quote_billing_address_management_v1_api import QuoteBillingAddressManagementV1Api


class TestQuoteBillingAddressManagementV1Api(unittest.TestCase):
    """ QuoteBillingAddressManagementV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.quote_billing_address_management_v1_api.QuoteBillingAddressManagementV1Api()

    def tearDown(self):
        pass

    def test_quote_billing_address_management_v1_assign_post(self):
        """
        Test case for quote_billing_address_management_v1_assign_post

        
        """
        pass

    def test_quote_billing_address_management_v1_assign_post_0(self):
        """
        Test case for quote_billing_address_management_v1_assign_post_0

        
        """
        pass

    def test_quote_billing_address_management_v1_get_get(self):
        """
        Test case for quote_billing_address_management_v1_get_get

        
        """
        pass

    def test_quote_billing_address_management_v1_get_get_0(self):
        """
        Test case for quote_billing_address_management_v1_get_get_0

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
