# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.checkout_data_totals_information_extension_interface import CheckoutDataTotalsInformationExtensionInterface


class TestCheckoutDataTotalsInformationExtensionInterface(unittest.TestCase):
    """ CheckoutDataTotalsInformationExtensionInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCheckoutDataTotalsInformationExtensionInterface(self):
        """
        Test CheckoutDataTotalsInformationExtensionInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.checkout_data_totals_information_extension_interface.CheckoutDataTotalsInformationExtensionInterface()
        pass


if __name__ == '__main__':
    unittest.main()
