# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.catalog_inventory_data_stock_item_interface import CatalogInventoryDataStockItemInterface


class TestCatalogInventoryDataStockItemInterface(unittest.TestCase):
    """ CatalogInventoryDataStockItemInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCatalogInventoryDataStockItemInterface(self):
        """
        Test CatalogInventoryDataStockItemInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.catalog_inventory_data_stock_item_interface.CatalogInventoryDataStockItemInterface()
        pass


if __name__ == '__main__':
    unittest.main()
