# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.customer_address_repository_v1_api import CustomerAddressRepositoryV1Api


class TestCustomerAddressRepositoryV1Api(unittest.TestCase):
    """ CustomerAddressRepositoryV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.customer_address_repository_v1_api.CustomerAddressRepositoryV1Api()

    def tearDown(self):
        pass

    def test_customer_address_repository_v1_delete_by_id_delete(self):
        """
        Test case for customer_address_repository_v1_delete_by_id_delete

        
        """
        pass

    def test_customer_address_repository_v1_get_by_id_get(self):
        """
        Test case for customer_address_repository_v1_get_by_id_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
