# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.catalog_product_attribute_management_v1_api import CatalogProductAttributeManagementV1Api


class TestCatalogProductAttributeManagementV1Api(unittest.TestCase):
    """ CatalogProductAttributeManagementV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.catalog_product_attribute_management_v1_api.CatalogProductAttributeManagementV1Api()

    def tearDown(self):
        pass

    def test_catalog_product_attribute_management_v1_assign_post(self):
        """
        Test case for catalog_product_attribute_management_v1_assign_post

        
        """
        pass

    def test_catalog_product_attribute_management_v1_get_attributes_get(self):
        """
        Test case for catalog_product_attribute_management_v1_get_attributes_get

        
        """
        pass

    def test_catalog_product_attribute_management_v1_unassign_delete(self):
        """
        Test case for catalog_product_attribute_management_v1_unassign_delete

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
