# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.catalog_product_media_attribute_management_v1_api import CatalogProductMediaAttributeManagementV1Api


class TestCatalogProductMediaAttributeManagementV1Api(unittest.TestCase):
    """ CatalogProductMediaAttributeManagementV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.catalog_product_media_attribute_management_v1_api.CatalogProductMediaAttributeManagementV1Api()

    def tearDown(self):
        pass

    def test_catalog_product_media_attribute_management_v1_get_list_get(self):
        """
        Test case for catalog_product_media_attribute_management_v1_get_list_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
