# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.quote_guest_cart_management_v1_api import QuoteGuestCartManagementV1Api


class TestQuoteGuestCartManagementV1Api(unittest.TestCase):
    """ QuoteGuestCartManagementV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.quote_guest_cart_management_v1_api.QuoteGuestCartManagementV1Api()

    def tearDown(self):
        pass

    def test_quote_guest_cart_management_v1_assign_customer_put(self):
        """
        Test case for quote_guest_cart_management_v1_assign_customer_put

        
        """
        pass

    def test_quote_guest_cart_management_v1_create_empty_cart_post(self):
        """
        Test case for quote_guest_cart_management_v1_create_empty_cart_post

        
        """
        pass

    def test_quote_guest_cart_management_v1_place_order_put(self):
        """
        Test case for quote_guest_cart_management_v1_place_order_put

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
