# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.cms_data_page_interface import CmsDataPageInterface


class TestCmsDataPageInterface(unittest.TestCase):
    """ CmsDataPageInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCmsDataPageInterface(self):
        """
        Test CmsDataPageInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.cms_data_page_interface.CmsDataPageInterface()
        pass


if __name__ == '__main__':
    unittest.main()
