# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.body_79 import Body79


class TestBody79(unittest.TestCase):
    """ Body79 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody79(self):
        """
        Test Body79
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.body_79.Body79()
        pass


if __name__ == '__main__':
    unittest.main()
