# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.tax_tax_rate_repository_v1_api import TaxTaxRateRepositoryV1Api


class TestTaxTaxRateRepositoryV1Api(unittest.TestCase):
    """ TaxTaxRateRepositoryV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.tax_tax_rate_repository_v1_api.TaxTaxRateRepositoryV1Api()

    def tearDown(self):
        pass

    def test_tax_tax_rate_repository_v1_delete_by_id_delete(self):
        """
        Test case for tax_tax_rate_repository_v1_delete_by_id_delete

        
        """
        pass

    def test_tax_tax_rate_repository_v1_get_get(self):
        """
        Test case for tax_tax_rate_repository_v1_get_get

        
        """
        pass

    def test_tax_tax_rate_repository_v1_get_list_get(self):
        """
        Test case for tax_tax_rate_repository_v1_get_list_get

        
        """
        pass

    def test_tax_tax_rate_repository_v1_save_post(self):
        """
        Test case for tax_tax_rate_repository_v1_save_post

        
        """
        pass

    def test_tax_tax_rate_repository_v1_save_put(self):
        """
        Test case for tax_tax_rate_repository_v1_save_put

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
