# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.bundle_data_bundle_option_interface import BundleDataBundleOptionInterface


class TestBundleDataBundleOptionInterface(unittest.TestCase):
    """ BundleDataBundleOptionInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBundleDataBundleOptionInterface(self):
        """
        Test BundleDataBundleOptionInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.bundle_data_bundle_option_interface.BundleDataBundleOptionInterface()
        pass


if __name__ == '__main__':
    unittest.main()
