# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.catalog_product_link_repository_v1_api import CatalogProductLinkRepositoryV1Api


class TestCatalogProductLinkRepositoryV1Api(unittest.TestCase):
    """ CatalogProductLinkRepositoryV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.catalog_product_link_repository_v1_api.CatalogProductLinkRepositoryV1Api()

    def tearDown(self):
        pass

    def test_catalog_product_link_repository_v1_delete_by_id_delete(self):
        """
        Test case for catalog_product_link_repository_v1_delete_by_id_delete

        
        """
        pass

    def test_catalog_product_link_repository_v1_save_put(self):
        """
        Test case for catalog_product_link_repository_v1_save_put

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
