# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.body_110 import Body110


class TestBody110(unittest.TestCase):
    """ Body110 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody110(self):
        """
        Test Body110
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.body_110.Body110()
        pass


if __name__ == '__main__':
    unittest.main()
