# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.quote_data_payment_interface import QuoteDataPaymentInterface


class TestQuoteDataPaymentInterface(unittest.TestCase):
    """ QuoteDataPaymentInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQuoteDataPaymentInterface(self):
        """
        Test QuoteDataPaymentInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.quote_data_payment_interface.QuoteDataPaymentInterface()
        pass


if __name__ == '__main__':
    unittest.main()
