# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.store_store_repository_v1_api import StoreStoreRepositoryV1Api


class TestStoreStoreRepositoryV1Api(unittest.TestCase):
    """ StoreStoreRepositoryV1Api unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.store_store_repository_v1_api.StoreStoreRepositoryV1Api()

    def tearDown(self):
        pass

    def test_store_store_repository_v1_get_list_get(self):
        """
        Test case for store_store_repository_v1_get_list_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
