# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.body_124 import Body124


class TestBody124(unittest.TestCase):
    """ Body124 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody124(self):
        """
        Test Body124
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.body_124.Body124()
        pass


if __name__ == '__main__':
    unittest.main()
