# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.sales_data_order_payment_interface import SalesDataOrderPaymentInterface


class TestSalesDataOrderPaymentInterface(unittest.TestCase):
    """ SalesDataOrderPaymentInterface unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSalesDataOrderPaymentInterface(self):
        """
        Test SalesDataOrderPaymentInterface
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.sales_data_order_payment_interface.SalesDataOrderPaymentInterface()
        pass


if __name__ == '__main__':
    unittest.main()
