# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Body23(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'attribute_set': 'EavDataAttributeSetInterface',
        'skeleton_id': 'int'
    }

    attribute_map = {
        'attribute_set': 'attributeSet',
        'skeleton_id': 'skeletonId'
    }

    def __init__(self, attribute_set=None, skeleton_id=None):
        """
        Body23 - a model defined in Swagger
        """

        self._attribute_set = None
        self._skeleton_id = None

        self.attribute_set = attribute_set
        self.skeleton_id = skeleton_id

    @property
    def attribute_set(self):
        """
        Gets the attribute_set of this Body23.

        :return: The attribute_set of this Body23.
        :rtype: EavDataAttributeSetInterface
        """
        return self._attribute_set

    @attribute_set.setter
    def attribute_set(self, attribute_set):
        """
        Sets the attribute_set of this Body23.

        :param attribute_set: The attribute_set of this Body23.
        :type: EavDataAttributeSetInterface
        """
        if attribute_set is None:
            raise ValueError("Invalid value for `attribute_set`, must not be `None`")

        self._attribute_set = attribute_set

    @property
    def skeleton_id(self):
        """
        Gets the skeleton_id of this Body23.

        :return: The skeleton_id of this Body23.
        :rtype: int
        """
        return self._skeleton_id

    @skeleton_id.setter
    def skeleton_id(self, skeleton_id):
        """
        Sets the skeleton_id of this Body23.

        :param skeleton_id: The skeleton_id of this Body23.
        :type: int
        """
        if skeleton_id is None:
            raise ValueError("Invalid value for `skeleton_id`, must not be `None`")

        self._skeleton_id = skeleton_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Body23):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
