# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Body6(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer': 'CustomerDataCustomerInterface',
        'password': 'str',
        'redirect_url': 'str'
    }

    attribute_map = {
        'customer': 'customer',
        'password': 'password',
        'redirect_url': 'redirectUrl'
    }

    def __init__(self, customer=None, password=None, redirect_url=None):
        """
        Body6 - a model defined in Swagger
        """

        self._customer = None
        self._password = None
        self._redirect_url = None

        self.customer = customer
        if password is not None:
          self.password = password
        if redirect_url is not None:
          self.redirect_url = redirect_url

    @property
    def customer(self):
        """
        Gets the customer of this Body6.

        :return: The customer of this Body6.
        :rtype: CustomerDataCustomerInterface
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """
        Sets the customer of this Body6.

        :param customer: The customer of this Body6.
        :type: CustomerDataCustomerInterface
        """
        if customer is None:
            raise ValueError("Invalid value for `customer`, must not be `None`")

        self._customer = customer

    @property
    def password(self):
        """
        Gets the password of this Body6.

        :return: The password of this Body6.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """
        Sets the password of this Body6.

        :param password: The password of this Body6.
        :type: str
        """

        self._password = password

    @property
    def redirect_url(self):
        """
        Gets the redirect_url of this Body6.

        :return: The redirect_url of this Body6.
        :rtype: str
        """
        return self._redirect_url

    @redirect_url.setter
    def redirect_url(self, redirect_url):
        """
        Sets the redirect_url of this Body6.

        :param redirect_url: The redirect_url of this Body6.
        :type: str
        """

        self._redirect_url = redirect_url

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Body6):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
