# coding: utf-8

"""
    Magento Community

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SalesDataShippingInterface(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'SalesDataOrderAddressInterface',
        'method': 'str',
        'total': 'SalesDataTotalInterface',
        'extension_attributes': 'SalesDataShippingExtensionInterface'
    }

    attribute_map = {
        'address': 'address',
        'method': 'method',
        'total': 'total',
        'extension_attributes': 'extension_attributes'
    }

    def __init__(self, address=None, method=None, total=None, extension_attributes=None):
        """
        SalesDataShippingInterface - a model defined in Swagger
        """

        self._address = None
        self._method = None
        self._total = None
        self._extension_attributes = None

        if address is not None:
          self.address = address
        if method is not None:
          self.method = method
        if total is not None:
          self.total = total
        if extension_attributes is not None:
          self.extension_attributes = extension_attributes

    @property
    def address(self):
        """
        Gets the address of this SalesDataShippingInterface.

        :return: The address of this SalesDataShippingInterface.
        :rtype: SalesDataOrderAddressInterface
        """
        return self._address

    @address.setter
    def address(self, address):
        """
        Sets the address of this SalesDataShippingInterface.

        :param address: The address of this SalesDataShippingInterface.
        :type: SalesDataOrderAddressInterface
        """

        self._address = address

    @property
    def method(self):
        """
        Gets the method of this SalesDataShippingInterface.
        Shipping method

        :return: The method of this SalesDataShippingInterface.
        :rtype: str
        """
        return self._method

    @method.setter
    def method(self, method):
        """
        Sets the method of this SalesDataShippingInterface.
        Shipping method

        :param method: The method of this SalesDataShippingInterface.
        :type: str
        """

        self._method = method

    @property
    def total(self):
        """
        Gets the total of this SalesDataShippingInterface.

        :return: The total of this SalesDataShippingInterface.
        :rtype: SalesDataTotalInterface
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this SalesDataShippingInterface.

        :param total: The total of this SalesDataShippingInterface.
        :type: SalesDataTotalInterface
        """

        self._total = total

    @property
    def extension_attributes(self):
        """
        Gets the extension_attributes of this SalesDataShippingInterface.

        :return: The extension_attributes of this SalesDataShippingInterface.
        :rtype: SalesDataShippingExtensionInterface
        """
        return self._extension_attributes

    @extension_attributes.setter
    def extension_attributes(self, extension_attributes):
        """
        Sets the extension_attributes of this SalesDataShippingInterface.

        :param extension_attributes: The extension_attributes of this SalesDataShippingInterface.
        :type: SalesDataShippingExtensionInterface
        """

        self._extension_attributes = extension_attributes

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SalesDataShippingInterface):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
